examples/animations.html
examples/basic.html
examples/blendshapes.html
examples/bones.html
examples/dnd.html
examples/firstperson.html
examples/lookat.html
examples/materials-debug.html
examples/meta.html
examples/mouse.html

次の動機から、`examples`の各コードに、dpiが通常と異なるモニタに対応するための`renderer.setPixelRatio( window.devicePixelRatio );`を加えました。
- より綺麗なサンプルを見せたい。
- 開発時の動作確認を見やすくしたい。
しかし、`@pixiv/three-vrm`の動作とは無関係な行が増えるデメリットも考えられますのでcontributorの方々のご意見を伺いたいです。

feat(examples): set the pixel ratio

---

README.md

README中の「via npm」のコード例の一部が「from HTML」のコードのままになっており、`THREE`にassignされた`THREE.GLTFLoader`, `THREE.VRM`を使用していました。

docs(readme): fix the example 'via npm'

---

.dependabot/config.yml

- dependabotの範囲を狭めました。
- Default assigneesからFMS_Catを外しました。

Narrow range of dependabot updates

---

src/vrm/springbone/VRMSpringBone.ts

- `VRMSpringBone.reset()` が正常に動作していなかったのを修正しました。

Make VRMSpringBone.reset() work properly

---

src/vrm/material/shaders/mtoon.frag

MToonのLitShadeRate DebugModeにおいて、MatCapやEmissiveなどの値が加算されていたため、これを修正しました。

MToon: Fix DebugLitShadeRate behavior

---

src/vrm/VRMImporter.ts
src/vrm/debug/VRMImporterDebug.ts
src/vrm/index.ts
src/vrm/removeUnnecessaryJoints.ts

`reduceBones` （ `removeUnnecessaryJoints` と名前を変更しました）の実行を任意としました。
つかいたい場合は、自分で `gltf.scene` を `removeUnnecessaryJoints` に入れる形となります。
VRM読み込み時のオプションで指定させても良かったかもしれませんが、どこにオプションを渡すべきかで悩みました……
`reduceBones` -> `removeUnnecessaryJoints`

make reduceBones (renamed to removeUnnecessaryJoints) optional

---

src/vrm/material/VRMMaterialImporter.ts

`Color.convertSRGBToLinear` がthreeの型定義に入ったようなので、該当箇所の `as any` を消しました。
https://github.com/mrdoob/three.js/blob/7a6d8dd4afcaf396ce61386822896d71977fb9ea/src/math/Color.d.ts#L126

these "as any" are no longer needed

---

.circleci/config.yml

To ensure docs are not broken in dependency updates

CI: add docs job, store types

---

examples/debug.html
examples/index.html

To ensure debug feature is not broken

examples: add debug.html

---

src/vrm/VRM.ts
src/vrm/VRMImporter.ts
src/vrm/blendshape/VRMBlendShapeImporter.ts
src/vrm/debug/VRMDebug.ts
src/vrm/debug/VRMImporterDebug.ts
src/vrm/debug/VRMLookAtImporterDebug.ts
src/vrm/debug/VRMSpringBoneImporterDebug.ts
src/vrm/firstperson/VRMFirstPersonImporter.ts
src/vrm/humanoid/VRMHumanoidImporter.ts
src/vrm/lookat/VRMLookAtImporter.ts
src/vrm/material/VRMMaterialImporter.ts
src/vrm/springbone/VRMSpringBoneImporter.ts
src/vrm/types/three.d.ts

branched from #267 
- it now imports `GLTF` from `three/examples/jsm/loaders/GLTFLoader`

Better gltf import

---

src/vrm/lookat/VRMCurveMapper.ts
src/vrm/lookat/VRMLookAtBlendShapeApplyer.ts
src/vrm/lookat/VRMLookAtBoneApplyer.ts
src/vrm/lookat/VRMLookAtImporter.ts
src/vrm/lookat/index.ts

Will close #294 
To prevent undesired potential name conflict
Since `CurveMapper` is already exposed to end developers, this is a breaking change
---
`CurveMapper` -> `VRMCurveMapper`

CurveMapper -> VRMCurveMapper

---

src/vrm/firstperson/VRMFirstPersonImporter.ts
src/vrm/springbone/VRMSpringBoneImporter.ts

Sequel of #91 
- Fix some z-axes that was inverted since vrm uses left-handed y-up for vectors
- `gravityDir` of spring bones
- `offset` of spring bone corriders
- `firstPersonBoneOffset` of first person
- gravityDir is now working properly
- It was not working properly because of an async operation

Fix some z-axis that was inverted

---

src/vrm/material/MToonMaterial.ts
src/vrm/material/VRMMaterialImporter.ts
src/vrm/material/shaders/mtoon.frag

- `emissionMap` property in MToon has miswritten as `emission` in code, fixed this
- `rimTexture` should be converted into appropriate color space since it's a color texture

fix some colorspace issues

---

src/vrm/VRM.ts
src/vrm/debug/VRMLookAtHeadDebug.ts
src/vrm/debug/VRMSpringBoneManagerDebug.ts

`GLTF.scene` is going to be `THREE.Group` in r114
This PR make it tolerable to be used in r114.
See: https://github.com/mrdoob/three.js/pull/18601

GLTF.scene is now okay to be a THREE.Group instead of THREE.Scene

---

src/vrm/material/shaders/mtoon.vert

outline width under `outlineWidthMode === WorldCoordinates` seems to be different a bit in three-vrm, being affected by its object scale.
This PR fixes this. Now the code is almost identical to the one in the original MToon code.
See: https://github.com/Santarh/MToon/blob/43b8a33053d59aba7efa44efd3214ba741d0d871/MToon/Resources/Shaders/MToonCore.cginc#L87-L89

[WIP] fix outlineWidthWorld

---

src/vrm/material/MToonMaterial.ts
src/vrm/material/VRMMaterialImporter.ts

rimTexture and uvAnimMaskTexture has malfunctioned because of ST values in vectorProperties.
This PR will fix this.

MToon: fix rimTexture and uvAnimMaskTexture

---

src/vrm/material/shaders/mtoon.frag

There is an issue on MToon that occurs when shadeToony is 1.0, in some specific GPU (tested @ GTX1080).
It seems that is caused by `smoothstep( 1.0, 1.0, x )` .
This PR will fix this.

MToon: fix a GPU specific issue that is caused by shadeToony = 1.0

---

examples/animations.html
examples/basic.html
examples/blendshapes.html
examples/bones.html
examples/debug.html
examples/dnd.html
examples/encoding.html
examples/envmap.html
examples/firstperson.html
examples/lookat-advanced.html
examples/lookat.html
examples/materials-debug.html
examples/meta.html
examples/mouse.html
package.json
src/vrm/springbone/VRMSpringBone.ts
yarn.lock

- `three` is now `0.116.0`
- Fix a type error that caused by the update of three.js

Bump three to r116

---

src/vrm/material/shaders/mtoon.frag

will resolve #430 
Replaced `#pragma unroll_loop` in shaders with `#pragma unroll_loop_start` / `end` .
It will dismiss the deprecation warning.

Shaders: update syntax of unroll_loop

---

src/vrm/material/MToonMaterial.ts

Will resolve #458
The diff explains everything

MToon: fix the direction of uv animation

---

src/vrm/debug/VRMSpringBoneDebug.ts
src/vrm/debug/VRMSpringBoneImporterDebug.ts
src/vrm/springbone/VRMSpringBone.ts
src/vrm/springbone/VRMSpringBoneImporter.ts
src/vrm/springbone/VRMSpringBoneManager.ts
src/vrm/utils/Matrix4WithInverseCache.ts

- "Center" feature is now functional as UniVRM
- `center` is set for each spring bones, defines a space for the calculation of spring bones
- 🚨 It now deserializes `center` of spring bones
- If you need the previous behavior, call `vrm.springBoneManager.setCenter(null)` after you import VRMs

VRMSpringBone: introducing center

---

src/vrm/debug/VRMSpringBoneDebug.ts
src/vrm/debug/VRMSpringBoneImporterDebug.ts
src/vrm/springbone/VRMSpringBone.ts
src/vrm/springbone/VRMSpringBoneImporter.ts
src/vrm/springbone/VRMSpringBoneParameters.ts
src/vrm/springbone/index.ts

- 🚨 The interface of `new VRMSpringBone` has changed
- Used to have so many arguments, now have one required argument and one optional parameters object ( `VRMSpringBoneParameters` )
- Most of members are now mutable
- Since they don't have to be readonly

refactor (VRMSpringBone): Make most of constructor parameters an interface / make readonly parameters mutable

---

examples/meta.html
src/vrm/VRM.ts
src/vrm/VRMImporter.ts
src/vrm/VRMUtils/extractThumbnailBlob.ts
src/vrm/VRMUtils/index.ts
src/vrm/meta/VRMMeta.ts
src/vrm/meta/VRMMetaImporter.ts
src/vrm/meta/VRMMetaImporterOptions.ts

- `vrm.meta` is now an interface `VRMMeta` instead of `VRMSchema.Meta`
- 🚨 Interface of `vrm.meta.texture` has been changed (`number` -> `THREE.Texture`)
- 🚨 Importing a VRM from a glTF now loads a thumbnail texture by default!
- Which may cause you unnecessary memory consumption
- Set `VRMMetaImporter.ignoreTexture = true` to disable this behavior
- ✨ now you can extract thumbnail as a Blob using `VRMUtils.extractThumbnailBlob(renderer, vrm, resolution)`
- See the `meta.html` example

Introducing VRMMeta, has an ability to load its thumbnail texture

---

src/vrm/VRMUtils/extractThumbnailBlob.ts

Sequel of #482 
Texture should be unassigned after the rendering

fix (VRMUtils.extractThumbnailBlob): forgot to unassign the texture

---

src/vrm/blendshape/VRMBlendShapeProxy.ts

I hope no one directly uses it...

`VRMBlendShapeProxy._blendShapeGroups` was unintentionally public

---

src/vrm/debug/VRMImporterDebug.ts

`MetaImporter` was not used in `VRMImporterDebug` , this PR fixes this

fix (VRMImporterDebug): MetaImporter was not used, fixing this

---

src/vrm/blendshape/VRMBlendShapeProxy.ts

VRMBlendShapeProxy へ _blendShapePresetMap の Getter の追加を提案します。
現状のVRMBlendShapeProxy.expressionsにはVRMの仕様で定義されているPresetNameではなく、ユーザーが設定するNameが格納されているためリップシンクなどの表情(A,Joy等)とその他(Unknown)の表情を区別することができません。
VRMBlendShapeProxy._blendShapePresetMapを参照することでユーザー定義の表情を区別することができるようになります。
```js
// unknownの表情の取得
const expressions = currentVrm.blendShapeProxy.expressions;
const presetMap = currentVrm.blendShapeProxy.blendShapePresetMap;
const presetExpressions = Object.values(presetMap);
const unknownExpressions = expressions.filter(name =>
!presetExpressions.includes(name)
);
```

add getter for presetNameMap

---

src/vrm/blendshape/VRMBlendShapeProxy.ts

Add a property `unknownGroupNames` to `VRMBlendShapeProxy`.
It enables us to get unknown blend shape group names.

feat (VRMBlendShapeProxy): Add a property, unknownGroupNames

---

src/vrm/humanoid/VRMHumanoid.ts

Should resolve #503 
- 🚨💡 Greatly changed the behavior of `getPose` / `setPose`
- It now explicitly receives / returns local, relative transforms that is described in `VRMPose`
- ✨ New method: `resetPose`
- It just resets the pose to its restPose (that should be T stance)
- 🚨💡 `restPose` is now explicitly not compatible with `getPose` / `setPose`
- If you want to reset its pose, I have introduced `resetPose` so use this instead

fix (humanoid): getPose / setPose is now working as intended

---

src/vrm/VRMUtils/extractThumbnailBlob.ts

Add OffscreenCanvas support for extractThumbnailBlob

---

tsconfig.json

Since `removeComments` was enabled in tsconfig, there were no doc comments on built typedef at all. This PR fixes this.

chore: remove removeComments setting from tsconfig

---

package.json
packages/three-vrm/package.json

precommit job (husky + lint-staged) was not working properly after monorepo #521 happened, this PR fixes this.

chore: fix monorepo precommit

---

.circleci/config.yml

CI has slightly been broken because of monorepo #521 . This PR fixes this.

chore: fix CI for monorepo

---

packages/three-vrm/examples/animations.html
packages/three-vrm/examples/basic.html
packages/three-vrm/examples/blendshapes.html
packages/three-vrm/examples/bones.html
packages/three-vrm/examples/debug.html
packages/three-vrm/examples/dnd.html
packages/three-vrm/examples/encoding.html
packages/three-vrm/examples/envmap.html
packages/three-vrm/examples/firstperson.html
packages/three-vrm/examples/lookat-advanced.html
packages/three-vrm/examples/lookat.html
packages/three-vrm/examples/materials-debug.html
packages/three-vrm/examples/meta.html
packages/three-vrm/examples/mouse.html
packages/three-vrm/package.json
packages/three-vrm/src/vrm/springbone/VRMSpringBone.ts
packages/three-vrm/src/vrm/utils/Matrix4InverseCache.ts
packages/three-vrm/src/vrm/utils/mat4InvertCompat.ts
yarn.lock

- 📦 Bump three.js to r123
- Had to replace `Matrix4.getInverse()` with `Matrix4.invert()`
- See: https://github.com/mrdoob/three.js/pull/20611
- Compat is implemented though, I believe it will still work properly in previous versions

Bump Three.js to r123

---

packages/three-vrm/src/vrm/humanoid/VRMHumanoid.ts
packages/three-vrm/src/vrm/lookat/VRMLookAtHead.ts

Sequel of #551 
I've replaced `Matrix4.getInverse()` but forgot replacing `Quaternion.inverse()`

fix: replace deprecated `Quaterion.inverse` with `invert`

---

packages/three-vrm/src/vrm/humanoid/VRMHumanoid.ts
packages/three-vrm/src/vrm/lookat/VRMLookAtHead.ts
packages/three-vrm/src/vrm/utils/quatInvertCompat.ts

Sequel of #555 
`Quaternion.invert` won't work with previous versions of Three.js, I've implemented a compat function

Implement compat of `Quaternion.invert` for previous versions of Three.js

---

packages/three-vrm/src/vrm/humanoid/VRMHumanoidImporter.ts

`VRMHumanoidImporter.import()`  assigns VRM Humanoid bone name to glTF node. But glTF node with its index of zero is unexpectedly excluded from that assignment.

Fix human bone assignment failure for gltf nodes[0]
